### ISSUE TITLE
e-mail uniqueness check fails when e-mail address not provided

### ISSUE THREAD

**Issue by fumuumuf** [iMerica/dj-rest-auth#117]
This issue is reprinted from https://github.com/Tivix/django-rest-auth/issues/485  (PR:https://github.com/Tivix/django-rest-auth/pull/537)

(When using social login)
> I traced the problem to the user not providing an e-mail address (which is valid in my use case), which results in a 400 error: "User is already registered with this e-mail address."

**Comment by vik-y** [comment]
I can also confirm that this bug exists in version 1.1.0, not sure if this has been fixed in later versions.

**Comment by fumuumuf** [comment]
Thank you for investigating.
