### ISSUE TITLE
login

### ISSUE THREAD

**Issue by skoomer** [iMerica/dj-rest-auth#122]
Why am I getting this error?

registration is successful, but I can not do login

I have models login for email option

{
    "non_field_errors": [
        "Unable to log in with provided credentials."
    ]
}

**Comment by iMerica** [comment]
Can you list the steps I can take to reproduce the issue locally?

**Comment by etoiledejean** [comment]
hi, i have the same issue i juste added django-allauth and add this config in my setting file : 

`
# this is config for django allAuth authentication .
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'none'
`

**Comment by skoomer** [comment]
Excuse me, it was my mistake but now I am faced with this.   and


I have a task to log in by email and password, how can I remove the username field?

 "POST /dj-rest-auth/login/ HTTP/1.1" 500 135192
Internal Server Error: /dj-rest-auth/login/
Traceback (most recent call last):

    raise self.model.DoesNotExist(
allauth.account.models.EmailAddress.DoesNotExist: EmailAddress matching query does not exist.

**Comment by vmesel** [comment]
Having the same problem around here. Registering the user with DRF documentation, and them trying to login with it via `/dj-rest-auth/login` endpoint.

**Comment by SilvioMessi** [comment]
In case you are using authentication via email and password you need to add the following parameters to your settings.py as described in the (allauth official documentation)[https://django-allauth.readthedocs.io/en/latest/installation.html]

```
AUTHENTICATION_BACKENDS = [
    ...
    # Needed to login by username in Django admin, regardless of allauth
    'django.contrib.auth.backends.ModelBackend',

    # allauth specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
    ...
]
```


@iMerica I think this is worth mentioning in the official documentation.

**Comment by themissingCRAM** [comment]
> In case you are using authentication via email and password you need to add the following parameters to your settings.py as described in the [allauth official documentation](https://django-allauth.readthedocs.io/en/latest/installation.html)
> 
> ```
> AUTHENTICATION_BACKENDS = [
>     ...
>     # Needed to login by username in Django admin, regardless of allauth
>     'django.contrib.auth.backends.ModelBackend',
> 
>     # allauth specific authentication methods, such as login by e-mail
>     'allauth.account.auth_backends.AuthenticationBackend',
>     ...
> ]
> ```
> 
> @iMerica I think this is worth mentioning in the official documentation.
Unfortunately adding this for me did not work, my email password login gave me a 500 error

**Comment by coelhogonzalo** [comment]
> In case you are using authentication via email and password you need to add the following parameters to your settings.py as described in the [allauth official documentation](https://django-allauth.readthedocs.io/en/latest/installation.html)
> 
> ```
> AUTHENTICATION_BACKENDS = [
>     ...
>     # Needed to login by username in Django admin, regardless of allauth
>     'django.contrib.auth.backends.ModelBackend',
> 
>     # allauth specific authentication methods, such as login by e-mail
>     'allauth.account.auth_backends.AuthenticationBackend',
>     ...
> ]
> ```
> 
> @iMerica I think this is worth mentioning in the official documentation.

> In case you are using authentication via email and password you need to add the following parameters to your settings.py as described in the [allauth official documentation](https://django-allauth.readthedocs.io/en/latest/installation.html)
> 
> ```
> AUTHENTICATION_BACKENDS = [
>     ...
>     # Needed to login by username in Django admin, regardless of allauth
>     'django.contrib.auth.backends.ModelBackend',
> 
>     # allauth specific authentication methods, such as login by e-mail
>     'allauth.account.auth_backends.AuthenticationBackend',
>     ...
> ]
> ```
> 
> @iMerica I think this is worth mentioning in the official documentation.

**Comment by coelhogonzalo** [comment]
> In case you are using authentication via email and password you need to add the following parameters to your settings.py as described in the [allauth official documentation](https://django-allauth.readthedocs.io/en/latest/installation.html)
> 
> ```
> AUTHENTICATION_BACKENDS = [
>     ...
>     # Needed to login by username in Django admin, regardless of allauth
>     'django.contrib.auth.backends.ModelBackend',
> 
>     # allauth specific authentication methods, such as login by e-mail
>     'allauth.account.auth_backends.AuthenticationBackend',
>     ...
> ]
> ```
> 
> @iMerica I think this is worth mentioning in the official documentation.

https://www.youtube.com/watch?v=HL_Lg9ye2ac THANKS SILVIO MESSI I WILL NEVER FORGET YOU
