### ISSUE TITLE
[Proposal] Change Login JWT payload "refresh_token" to "refresh"

### ISSUE THREAD

**Issue by dohyungp** [iMerica/dj-rest-auth#142]
Hello, Team!
First of all, I'm using it so well. Many thanks!

In [dj_rest_auth/views.py - LoginView class](https://github.com/jazzband/dj-rest-auth/blob/73c7fb80afc33b3b4421c35408a82e55f1d7228b/dj_rest_auth/views.py#L74-L79), A payload of the response have keys(`access_token`, `refresh_token`).

```
        if getattr(settings, 'REST_USE_JWT', False):
            data = {
                'user': self.user,
                'access_token': self.access_token,
                'refresh_token': self.refresh_token
            }
```

But when I try logout or refresh, I should request with `refresh` key. 

For example,
```
curl -x post /dj-rest-auth/token/refresh/ -d '{"refresh": "...."}'
```

For consistency I propose to remove `_token` from Login response keys(`access_token`, `refresh_token`).

Please feel free comment my ask! Thanks!

**Comment by mevans** [comment]
Yeah this is pretty annoying, would be nice if this was configurable
