### ISSUE TITLE
Not using set-cookie for refresh token

### ISSUE THREAD

**Issue by Luctia** [iMerica/dj-rest-auth#190]
Is it intended or a bug that the JWT refresh token isn't being set using set-cookie, and instead just being sent with the response to `/login` (or refresh)? If it's intended use, I assume it would have to be managed by the client, which seems insecure.

**Comment by SpicyPaper** [comment]
In the LoginView class of this project you can see in the method get_response(self) that the refresh token is set as a cookie.
https://github.com/jazzband/dj-rest-auth/blob/06eeac95e0499640bf10f30a13fabd5ae33f73d8/dj_rest_auth/views.py#L123-L132

Of course you need to be sure to use correctly the settings of the package. In your case put REST_USE_JWT param to True, should work.
https://github.com/jazzband/dj-rest-auth/blob/06eeac95e0499640bf10f30a13fabd5ae33f73d8/dj_rest_auth/views.py#L105

**Comment by Luctia** [comment]
@SpicyPaper I just looked into it again after some time. Obviously I had set `REST_USE_JWT` to true, but after looking into the code you mentioned I noticed the setting `JWT_AUTH_REFRESH_COOKIE` which doesn't seem to be mentioned in the docs, but is set to None when you don't set it. Since it wasn't mentioned in the docs, I hadn't set it, it was set to None and the refresh token wasn't set.
