### ISSUE TITLE
Correct settings for Telegram auth?

### ISSUE THREAD

**Issue by fialkovod** [iMerica/dj-rest-auth#210]
Allauth package have Talegram support.
Following instruction on https://core.telegram.org/widgets/login I can get response from telegram with id and user details in GET parameters of response. So we need to forward this info to allauth, but we have a choice of code or access_token fields in login view of dj-rest-auth
So how can we setup view with adapter_class, client_class as far as we jast need to pass response with GET to allauth?

**Comment by iMerica** [comment]
Hi, this package is not a REST extension of All Auth. We just happen to have an optional registration capability that leverages All Auth by chance. I suggest reading through the All Auth code and the login/registration Views in this package to craft a solution that works.
