### ISSUE TITLE
Expose logout logic through dj-rest-auth config

### ISSUE THREAD

**Issue by mjmaurer** [iMerica/dj-rest-auth#219]
There are a two places where dj-rest-auth [assumes the fields](https://github.com/jazzband/dj-rest-auth/blob/732935d168bc2a325c0bdd5ddf831b509b53cff3/dj_rest_auth/views.py#L167) of the user model / token.

`auth_token` for my user model is actually a set, so `delete()` won't work. Easy enough to extend LogoutView, but this would be a nice improvement.

**Comment by iMerica** [comment]
Thanks for opening up this ticket. Currently, expanding the number of config parameters to cover every possible edge case is not something we want to do in this package. Feel free to extend the class and add your own biz logic.
