### ISSUE TITLE
Mismatch between Read the docs and repository

### ISSUE THREAD

**Issue by txels** [iMerica/dj-rest-auth#222]
The README in this repo points to a readthedocs project that is not associated with this repo.

I was setting up dj-rest-auth following the docs in readthedocs and was very confused with the mismatch between available versions until I realised that the readthedocs version is built from https://github.com/iMerica/dj-rest-auth.git

As a result of the way the docs build is set up, the documented versions in readthedocs do not correspond with tags/releases in this repo.

**Comment by txels** [comment]
Hmm I just realised that the github project in readthedocs actually redirects here. However, there still is a version mistmatch.

Readthedocs:

![image](https://user-images.githubusercontent.com/874958/106381359-6dab3080-63b8-11eb-8954-5ebc27d8504f.png)

Tags in this repo:

![image](https://user-images.githubusercontent.com/874958/106381373-861b4b00-63b8-11eb-8106-f7d9139a4b73.png)

**Comment by iMerica** [comment]
Is there a problem that is manifested from whatever issue you're pointing out? I can't find one. 

Read the Docs and the Github Releases page both share the latest version 2.1.3 and earliest version 0.9.5.

**Comment by iMerica** [comment]
Not finding a version mismatch. If you can list steps to reproduce, I'll re-open this ticket and investigate.

**Comment by txels** [comment]
Hmmm. Odd. I see that it is now showing me a version 2.1.3 that wasn't appearing before (see previous screenshot).

![image](https://user-images.githubusercontent.com/874958/107144186-c55a1680-6939-11eb-9f2d-813e851106bf.png)

Apologies for the inconveniencies caused.
