### ISSUE TITLE
CSRF Failed

### ISSUE THREAD

**Issue by jeffpohlmeyer** [iMerica/dj-rest-auth#241]
This is related to #40 

My urlpatterns are set up as
```
urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('dj_rest_auth.urls')),
    path('auth/registration/', include('dj_rest_auth.registration.urls')),
]
```
and my AllAuth settings right now are simply
```
SITE_ID = 1
```

I'm able to submit a register request to http://localhost:8000/auth/registration/, which returns a key.  I then try to send a post request with said key to http://localhost:8000/auth/registration/verify-email/ and I get a 403 response code with the response body of
```
{
    "detail": "CSRF Failed: CSRF token missing or incorrect."
}
```
Not sure if there's a setting I'm missing but in looking through all of the issues and searching for "CSRF" on both the docs for dj-rest-auth and django-allauth didn't return anything where this seemed to show up for other people.

**Comment by jeffpohlmeyer** [comment]
Update:
I realized it was because I still had session auth in there.  Now, though, I try to pass said key back in a post request and I get a 404 response.

**Comment by nahasco** [comment]
What do you mean you had session auth in there? It was working for me and then I did some changes and now I am getting the same error you're getting.

**Comment by jeffpohlmeyer** [comment]
> What do you mean you had session auth in there? It was working for me and then I did some changes and now I am getting the same error you're getting.

I genuinely don't remember. It was 16 months ago
