### ISSUE TITLE
refresh token is not shown in the swagger

### ISSUE THREAD

**Issue by HodaJafari** [iMerica/dj-rest-auth#247]
https://github.com/iMerica/dj-rest-auth/blob/2e2ce84ce355dfe4e6c3f64552734020a3efcf17/dj_rest_auth/views.py#L168
Does anyone know why refresh token is not shown in the swagger when I enable 'rest_framework_simplejwt.token_blacklist'?
and how can I fix it? 

![image](https://user-images.githubusercontent.com/13479916/114499987-7633a900-9c3c-11eb-9e55-19c9614af813.png)

**Comment by Luctia** [comment]
Are you certain it works if you don't have `rest_framework_simplejwt.token_blacklist` enabled?

**Comment by HodaJafari** [comment]
if rest_framework_simplejwt.token_blacklist is not enabled, I don't need to pass "refresh" token. So the swagger works fine as it is

**Comment by Luctia** [comment]
I think you could use JWT without using a blacklist. Anyway, have you set `JWT_AUTH_REFRESH_COOKIE = 'my-refresh-token'` in your settings?

**Comment by HodaJafari** [comment]
Yes I don't have any issue with using JWT with/without blacklist. APIs and everything are OK.
The only problem is in the swagger. 
Swagger doesn't show me right parameters as an input (refresh token)
I just wanted to know how can I change it.

**Comment by HodaJafari** [comment]
I just fixed it by overriding LogoutView


`from dj_rest_auth.views import LogoutView
from django.utils.decorators import method_decorator
from drf_yasg import openapi
from drf_yasg.utils import swagger_auto_schema


@method_decorator(
    name="post",
    decorator=swagger_auto_schema(
        request_body=openapi.Schema(
            type=openapi.TYPE_OBJECT,
            required=["refresh"],
            properties={"refresh": openapi.Schema(type=openapi.TYPE_STRING)},
        ),
    ),
)
class CustomLogoutView(LogoutView):
    def post(self, request, *args, **kwargs):
        return self.logout(request)
`
