### ISSUE TITLE
Add ability to override the SocialLoginSerializer

### ISSUE THREAD

**Issue by cmraible** [iMerica/dj-rest-auth#254]
In my application, I override the RegisterSerializer to do some further validation (I require users to have an invite before signing up). I'd like to do the same thing with social logins, but currently there is no way to override the SocialLoginSerializer in my application settings the way I can with the RegisterSerializer.

**Comment by cmraible** [comment]
Realized I can override the serializer for a social login in the login view!

**Comment by Jayesh-Mahato** [comment]
@cmraible Can you please have a look at my issues posted here in Issue  #271  and guide me. It is similar to your issue.
