### ISSUE TITLE
Problem with `CamelCaseRenderer/Parser` and `PasswordResetConfirmSerializer`

### ISSUE THREAD

**Issue by Luctia** [iMerica/dj-rest-auth#262]
In my project, I have added
```python
REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": (
        'djangorestframework_camel_case.render.CamelCaseJSONRenderer',
        'djangorestframework_camel_case.render.CamelCaseBrowsableAPIRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'djangorestframework_camel_case.parser.CamelCaseJSONParser',
    ),
}
```
Because I want to make sure my client gets camelCase responses as that is the standard for JS, but I want to use snake_case in my Python code. So far, this has worked perfectly fine, but now I want to implement the _forgot password_ feature and I run into an issue. When I send a POST such as `{uid: "someuid", token: "sometoken", newPassword1: "some_password", newPassword2: "some_password"}`, I get back `{"newPassword1":["This field is required."],"newPassword2":["This field is required."]}`. The same happens when I use snake_case in my POST request. When I remove these renderers/parsers and I send snake_case, it works, however, in the interest of the rest of my project, I'm not willing to just sacrifice that. So my question is: is there a way to specify renderers/parsers for these parts specifically (since the `PasswordResetConfirmSerializer` seems to just ignore them or something)?

Edit:
If I copy the `PasswordResetConfirmView` from source to a custom view, I can add:
```python
parser_classes = [CamelCaseJSONParser, CamelCaseMultiPartParser, CamelCaseFormParser]
renderer_classes = [CamelCaseJSONRenderer]
```
This does nothing. In the end, I just set them to the regular DRF parser/renderers, so now I can POST with camel_case. It's a shame it's the only way I can think of, but I guess it works. I'll leave this open for a couple of days in case people have more elegant suggestions and then I'll close it.

**Comment by bennettrogers** [comment]
I just ran into the same issue. The docs for `djangorestframework_camel_case` offer a suggestion that worked for me. [Here](https://github.com/vbabiy/djangorestframework-camel-case#underscoreize-options) is the relevant section of the docs. I adapted the below snippet into my custom viewset action and it's no longer inserting the underscore into the serializer fields for that action.

```python
from djangorestframework_camel_case.parser import CamelCaseJSONParser
from rest_framework.generics import CreateAPIView

class NoUnderscoreBeforeNumberCamelCaseJSONParser(CamelCaseJSONParser):
    json_underscoreize = {'no_underscore_before_number': True}

class MyView(CreateAPIView):
    queryset = MyModel.objects.all()
    serializer_class = MySerializer
    parser_classes = (NoUnderscoreBeforeNumberCamelCaseJSONParser,)

```

**Comment by MimmyJau** [comment]
Alternatively using the `ignore_keys` field, we can add the following settings.

```
REST_FRAMEWORK = {
    # ...
    "JSON_UNDERSCOREIZE": {
        # ...
        "ignore_keys": ("password1", "password2"),
        # ...
    },
    # ...
}
```

On another note, is there a way we can fix this by default? Or as a low-hanging-fruit just add this to the docs?
