### ISSUE TITLE
BUG: cannot import name 'DefaultPasswordResetForm' from 'django.contrib.auth.forms'

### ISSUE THREAD

**Issue by fabioaccetta** [iMerica/dj-rest-auth#279]
### Environment (`python 3.8` without `django-allauth`)

```python
Django==3.2.5
djangorestframework==3.12.4
dj-rest-auth==2.1.8
django-cors-headers==3.7.0
djangorestframework-simplejwt==4.7.2
django-cors-headers==3.7.0
```

### Reproduction
- update urls.py inside my api app:
```python
 urls.path('auth/', urls.include('dj_rest_auth.urls'), name='auth'),
```
- execute `./manage.py runserver`

### Expected behaviour
A working rest application with jwt login enabled

### Actual output
```
[...]
  File "/usr/local/lib/python3.8/site-packages/dj_rest_auth/urls.py", line 4, in <module>
    from dj_rest_auth.views import (
  File "/usr/local/lib/python3.8/site-packages/dj_rest_auth/views.py", line 16, in <module>
    from .app_settings import (
  File "/usr/local/lib/python3.8/site-packages/dj_rest_auth/app_settings.py", line 3, in <module>
    from dj_rest_auth.serializers import JWTSerializer as DefaultJWTSerializer
  File "/usr/local/lib/python3.8/site-packages/dj_rest_auth/serializers.py", line 22, in <module>
    from .forms import PasswordResetForm
  File "/usr/local/lib/python3.8/site-packages/dj_rest_auth/forms.py", line 16, in <module>
    from django.contrib.auth.forms import DefaultPasswordResetForm
ImportError: cannot import name 'DefaultPasswordResetForm' from 'django.contrib.auth.forms' (/usr/local/lib/python3.8/site-packages/django/contrib/auth/forms.py)
```
### Possible solution

It seems that this class does not exist inside Django Auth Forms:

https://github.com/iMerica/dj-rest-auth/blob/218747fb6188c3f2ba0c0b97cc20a871e5efe255/dj_rest_auth/forms.py#L16

**Comment by bufke** [comment]
This looks to be a regression in the recently released 2.1.8. Downgrading to 2.1.7 seems to work around the issue until it's fixed.

**Comment by surister** [comment]
Are new releases even tested? Perhaps a CI job should be set up to catch breaking commits/pushes.

**Comment by iMerica** [comment]
I've submitted a PR to fix this:

https://github.com/iMerica/dj-rest-auth/pull/280

Can someone have a look?

**Comment by vonrfdivino** [comment]
Still output an ImportError for me. 

[LOG]
`ImportError: cannot import name 'DefaultPasswordResetForm' from 'django.contrib.auth.forms'`

[requirements.txt]
asgiref==3.4.1
dj-rest-auth==2.1.8
Django==3.2.5
django-cors-headers==3.7.0
djangorestframework==3.12.4
python-dotenv==0.18.0
pytz==2021.1
sqlparse==0.4.1

**Comment by iMerica** [comment]
This should be fixed in 2.1.9

**Comment by jeroenbrouwer** [comment]
> This should be fixed in 2.1.9

It was fixed in 2.1.9, but the fix is not included in 2.1.10.

**Comment by surister** [comment]
The new error in 2.1.10 is slightly different, not the same one

**Comment by jeroenbrouwer** [comment]
> The new error in 2.1.10 is slightly different, not the same one

Actually, it is the exact same error... the fix was removed in this commit https://github.com/iMerica/dj-rest-auth/commit/3d210420fc37b940398c5e3500ddb9cf9e008613
