### ISSUE TITLE
No error for non existent email

### ISSUE THREAD

**Issue by chymdyugah** [iMerica/dj-rest-auth#287]
Sending an email to reset password does not return any error if the email does not exist for a user but returns a success response instead.

**Comment by thomas545** [comment]
Added PR resolved this problem just waiting for merge 
PR: [#293 ](https://github.com/iMerica/dj-rest-auth/pull/293)

**Comment by eriol** [comment]
It's the correct thing to do to not make an attacker harvest emails of registered users, please see OSWAP cheat sheet for more details: https://cheatsheetseries.owasp.org/cheatsheets/Forgot_Password_Cheat_Sheet.html#forgot-password-request

**Comment by Luctia** [comment]
eriol is correct, this issue should be closed @chymdyugah, see also the feedback from iMerica on #293

**Comment by chymdyugah** [comment]
Thanks for the referral... Understood. 

Closing now
