### ISSUE TITLE
Unaccesible class when importing url

### ISSUE THREAD

**Issue by JavierSab** [iMerica/dj-rest-auth#295]
On version 2.1.10, when importing the urls as:

```
urlpatterns = [
    ...,
    path('dj-rest-auth/', include('dj_rest_auth.urls'))
]
```

I get the following traceback:
```

File "/usr/local/lib/python3.7/site-packages/dj_rest_auth/forms.py", line 17, in <module>
    class AllAuthPasswordResetForm(DefaultPasswordResetForm):
NameError: name 'DefaultPasswordResetForm' is not defined
```

I have rolled back to 2.1.9 and it does not happen.

**Comment by Tatchakorn** [comment]
Have you installed django-allauth?
I also had the same problem. but I just installed django-allauth, put it in INSTALLED_APPS and it worked just fine.

**Comment by Luctia** [comment]
Have this issue too, worked fine before.

**Comment by surister** [comment]
@Tatchakorn Installing allauth is not a fix, you are suppose to be able to use dj-rest-auth without allauth

**Comment by surister** [comment]
#297 Fixes this Issue.
