### ISSUE TITLE
The password reset returns OK even on non-existing email

### ISSUE THREAD

**Issue by amartya-dev** [iMerica/dj-rest-auth#327]
The expected behavior should probably be to return an error stating that the email does not exist, I am using allauth with dj_rest_auth

**Comment by scallywag** [comment]
This is standard Django behaviour, cf. https://docs.djangoproject.com/en/3.2/topics/auth/default/#django.contrib.auth.views.PasswordResetView

**Comment by amartya-dev** [comment]
Yeah, makes sense, thanks for the reply though
