### ISSUE TITLE
Django 4.0 Facebook provider broken in allauth 

### ISSUE THREAD

**Issue by Tobeyforce** [iMerica/dj-rest-auth#358]
Django deprecated urlquote() in 4.0: https://docs.djangoproject.com/en/4.0/releases/4.0/
This caused an error in the facebook provider class in allauth.
This has been fixed in the latest version. I therefore suggest bumping whatever version is installed when running  pip install 'dj-rest-auth[with_social]', but perhaps compatability first needs to be ascertained with django 4.0.

Error is thrown using allauth 0.44.0 and earlier
Fixed sometime inbetween here.

Overall I hope to see dj-rest-auth to be compatible with django 4.0 and drf 3.13.0

**Comment by iMerica** [comment]
I just tested Django 4.0 with DRF 3.13. All tests passed.
