### ISSUE TITLE
is this a drop in replacement for django-rest-auth

### ISSUE THREAD

**Issue by getorca** [iMerica/dj-rest-auth#360]
Is this a drop in replacement for django-rest-auth?

**Comment by webontos** [comment]
@getorca quoting from DRF site (https://www.django-rest-framework.org/api-guide/authentication/): 

"This library provides a set of REST API endpoints for registration, authentication (including social media authentication), password reset, retrieve and update user details, etc. By having these API endpoints, your client apps such as AngularJS, iOS, Android, and others can communicate to your Django backend site independently via REST APIs for user management.

There are currently two forks of this project.

Django-rest-auth is the original project, but is not currently receiving updates.
Dj-rest-auth is a newer fork of the project.
"
