### ISSUE TITLE
Authenticate on a backend server with Google account

### ISSUE THREAD

**Issue by bene25** [iMerica/dj-rest-auth#365]
Hello, I already have dj-rest-auth in my app. 
How can I authenticate user on a backend server with Google account - https://developers.google.com/identity/sign-in/android/backend-auth

I dont want to reinvent the wheel, maybe you could point me out how to do this with dj-rest-auth
Thanks in advance!

**Comment by imran6932** [comment]
it's already on dj rest auth docs please read carefully and implement the code to login with google.
[https://dj-rest-auth.readthedocs.io/en/latest/installation.html](url)

**Comment by bene25** [comment]
So I made it up almost like described [here](https://gonzafirewall.medium.com/google-oauth2-and-django-rest-auth-92b0d8f70575)

But now I got 
`django.urls.exceptions.NoReverseMatch: Reverse for 'account_confirm_email' not found. 'account_confirm_email' is not a valid view function or pattern name.`
So my question is, if email is verified by social provider, in my case Google and I have this key-value pair in response 
`'email_verified': True, `
Should I verify email again in case if its mandatory?

**Comment by imran6932** [comment]
> So I made it up almost like described [here](https://gonzafirewall.medium.com/google-oauth2-and-django-rest-auth-92b0d8f70575)
> 
> But now I got `django.urls.exceptions.NoReverseMatch: Reverse for 'account_confirm_email' not found. 'account_confirm_email' is not a valid view function or pattern name.` So my question is, if email is verified by social provider, in my case Google and I have this key-value pair in response `'email_verified': True, ` Should I verify email again in case if its mandatory?

Its for custom sign up when user create an account with email user need to verify with verification email link, you can turn off this in settings.py

**Comment by bene25** [comment]
got it, I want get data from provider and "auto verify" email if its verified by google or facebook. In case email sign up I want to leave email verification mandatory, so there would be email confirmation sent.

**Comment by imran6932** [comment]
> got it, I want get data from provider and "auto verify" email if its verified by google or facebook. In case email sign up I want to leave email verification mandatory, so there would be email confirmation sent.

Once you login with google, google response a token you have to provide this token in Google login api then it's auto create a account for u in database and response jwt token and user profile. You can use that email to login only with google not direct login.

**Comment by bene25** [comment]
> You can use that email to login only with google not direct login.
yes, but how auto verify email if its already verified by google?

**Comment by imran6932** [comment]
> > You can use that email to login only with google not direct login.
> 
> yes, but how auto verify email if its already verified by google?

Account already created with google email and verified you don't need to verify that email again if u try to  register with same email it's raise an error email already exist.

**Comment by bene25** [comment]
> Account already created with google email and verified you don't need to verify that email again

Not really
![image](https://user-images.githubusercontent.com/11219968/153827959-1c91ff2d-ee47-4288-a09a-eed6401e5f1c.png)

**Comment by bene25** [comment]
So I disabled email verification for social accounts

**Comment by imran6932** [comment]
> 

when you logged in through social account it will show on social account model which is in bottom, and in email addresses will show only email which is custom sign up and once you clicked on confirmation email then verified will true else false.

**Comment by imran6932** [comment]
> 

don't need to verify email with social login.
