### ISSUE TITLE
Reverse for 'password_reset_confirm' not found

### ISSUE THREAD

**Issue by milano-slesarik** [iMerica/dj-rest-auth#370]
Hello, I just got this error when sending POST to `password/reset/`.

There are these patterns in the app:

```
    path('password/reset/', PasswordResetView.as_view(), name='rest_password_reset'),
    path('password/reset/confirm/', PasswordResetConfirmView.as_view(), name='rest_password_reset_confirm'),
```

But this code call is without `rest`

```
path = reverse( …
                'password_reset_confirm',
                args=[user_pk_to_url_str(user), temp_key],
            )
```

I'm not sure if that's a bug or I'm missing something. Thanks

**Comment by psilva1982** [comment]
hi milano, i have same problem. 

on [faq](https://dj-rest-auth.readthedocs.io/en/latest/faq.html) 

I get an error: Reverse for ‘password_reset_confirm’ not found.

You need to add password_reset_confirm url into your urls.py (at the top of any other included urls). Please check the urls.py module inside demo app example for more details.

[urls.py](https://github.com/iMerica/dj-rest-auth/blob/master/demo/demo/urls.py)

I **solved** with this then:
    re_path(r'^authentication/password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

**Comment by jeffepok** [comment]
Is that a bug? Cos I was facing the same problem.

**Comment by iMerica** [comment]
See [FAQ](https://dj-rest-auth.readthedocs.io/en/latest/faq.html
).
