### ISSUE TITLE
when setting dj_rest_auth as default auth, DRF web view login doesn't work

### ISSUE THREAD

**Issue by robertwt7** [iMerica/dj-rest-auth#371]
Hi there,

This might be a stupid question,

but if i do this:
```
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "dj_rest_auth.jwt_auth.JWTCookieAuthentication",
    ]
}
```

Then my login in DRF api explorer doesn't work. I have to add the `SessionAuthentication` back in order for the login to work:
```
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "dj_rest_auth.jwt_auth.JWTCookieAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ]
}
```

Is there any way that it can work without adding session auth?

I remember in my other app i use the default JWT and the login works just fine:
```
REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}
```

**Comment by imran6932** [comment]
you can use 
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ['dj_rest_auth.jwt_auth.JWTAuthentication']
}

it will work

**Comment by robertwt7** [comment]
Hi @imran6932 , thanks for your reply

what's the difference between `dj_rest_auth.jwt_auth.JWTAuthentication` and `'dj_rest_auth.jwt_auth.JWTCookieAuthentication'`?
