### ISSUE TITLE
 Is there a way to only allow social sign in and not registration

### ISSUE THREAD

**Issue by brsc2909** [iMerica/dj-rest-auth#378]
what I want to do is have users register using a standard registration page and then have them link their facebook account once in the application which will then allow them to sign in using the "Sign in with facebook" button. So if the users doesn't have an account the Sign in button shouldn't work. however at the moment if a user clicks the FB sign in button A blank account gets created. is there a way to only allow social sign in and not registration ?

**Comment by rollersteaam** [comment]
@brsc2909 You're looking for `SOCIALACCOUNT_AUTO_SIGNUP` https://django-allauth.readthedocs.io/en/latest/configuration.html. In your app's settings, set `SOCIALACCOUNT_AUTO_SIGNUP = False`. The docs for this library are fairly lackluster unfortunately, for most behaviour that you want to tweak you need to go down to the allauth layer.

**Comment by Emnalyeriar** [comment]
> @brsc2909 You're looking for `SOCIALACCOUNT_AUTO_SIGNUP` https://django-allauth.readthedocs.io/en/latest/configuration.html. In your app's settings, set `SOCIALACCOUNT_AUTO_SIGNUP = False`. The docs for this library are fairly lackluster unfortunately, for most behaviour that you want to tweak you need to go down to the allauth layer.

I also thought that it should work this way but it looks like dj-rest-auth doesn't use this setting? Setting this to False still creates a new user if there is none.

**Comment by iMerica** [comment]
Seems like unimplemented behavior. `SOCIALACCOUNT_AUTO_SIGNUP` is a feature of Django All Auth.
