### ISSUE TITLE
Handle ImmediateHttpResponse in SocialLoginSerializer validate

### ISSUE THREAD

**Issue by riteshbisht** [iMerica/dj-rest-auth#379]
After calling  complete_social_login(request, login) 
(https://github.com/iMerica/dj-rest-auth/blob/2d455333d5ae9910adb43de3488013ee2028f2eb/dj_rest_auth/registration/serializers.py#L151)

ImmediateHttpResponse is not bieng handled returned from complete_social_login 

(https://github.com/pennersr/django-allauth/blob/0.47.0/allauth/socialaccount/helpers.py#L153)

it does not raise validation error, shouldn't we handle this in validate or do we need to explicitly handle it by overidering SocialLoginSerializer.

Anyone else facing this issue?

Thanks in Advance!!

**Comment by iMerica** [comment]
Merged. Thank you for raising this issue.
