### ISSUE TITLE
Does PasswordResetConfirmView.py auto populate uid and token?

### ISSUE THREAD

**Issue by themissingCRAM** [iMerica/dj-rest-auth#382]
The view definitely does not populate on my end but password_reset_confirm.html in the demo template folder seems to do that.
Any help appreciated.

![image](https://user-images.githubusercontent.com/60025340/155844277-84a595ea-175c-45cf-a621-7841d44f2c35.png)

url.py
```
    path("dj-rest-auth/password/reset/confirm/<str:uid>/<str:token>/",
        # TemplateView.as_view(template_name="password_reset_confirm.html"),
        PasswordResetConfirmView.as_view(),
         name='resend-email-verification'
    ),  

```

**Comment by riteshbisht** [comment]
I guess  password_reset_confirm.html in demo/templates has javascript that runs when the page is rendered using TemplateView, Following is the JS Snippet used.

{% block script %}
    <script type="text/javascript">
        var url_elements = window.location.pathname.split('/');
        if (url_elements.length == 6){
            var uid = url_elements[url_elements.length - 3];
            if (uid !== undefined){
                $('input[name=uid]').val(uid);
            }
            var token = url_elements[url_elements.length - 2];
            if (token !== undefined){
                $('input[name=token]').val(token);
            }
        }
    </script>
{% endblock %}
 
 BUT what you are seeing is UI of browasable API of django rest framework that does not have this functionality for reading url and populating form field unless you tell it to.
 
 if you want your browable API to do this, you can create templates/rest_framework/api.html file and insert follwing code inside it, I think this will populate both uid and token field
 
 
 {% extends "rest_framework/base.html" %}

{% block style %}
    {{ block.super }}
        <style>
            #btn-link {
                border: none;
                outline: none;
                background: none;
                display: block;
                padding: 3px 20px;
                clear: both;
                font-weight: 400;
                line-height: 1.42857143;
                color: #A30000;
                white-space: nowrap;
                width: 100%;
                text-align: left;
            }
            #btn-link:hover {
                background: #EEEEEE;
                color: #C20000;
            }
        </style>
{% endblock %}

{% block userlinks %}
    {% if user.is_authenticated or response.data.access_token %}
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                {% firstof user.username 'Registered' %}
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu dropdown-menu-right">
                {% url 'rest_user_details' as user_url %}
                <li><a href="{{ user_url }}">User</a></li>
                <li>
                    {% url 'rest_logout' as logout_url %}
                    <form action="{{ logout_url }}" method="post">
                        {% csrf_token %}
                        <button type="submit" id="btn-link">Logout</button>
                    </form>
                </li>
            </ul>
        </li>
    {% else %}
        {% url 'rest_login' as login_url %}
        <li><a href="{{ login_url }}">Login</a></li>
        {% url 'rest_register' as register_url %}
        <li><a href="{{ register_url }}">Register</a></li>
    {% endif %}
{% endblock %}


{% block script %}
    {{block.super}}
    <script type="text/javascript">
        var url_elements = window.location.pathname.split('/');
        console.log(url_elements)
        var uid = url_elements[url_elements.length - 3];
        if (uid !== undefined){
            $('input[name=uid]').val(uid);
        }
        var token = url_elements[url_elements.length - 2];
        if (token !== undefined){
            $('input[name=token]').val(token);
        }
    </script>
{% endblock %}

**Comment by themissingCRAM** [comment]
I have confused myself I guess. I think i have tried the first block code but it did not work. I was using `TemplateView.as_view()`

But your second code block works with `PasswordResetConfirmView.as_view()`. Thank you so much for your help
