### ISSUE TITLE
Proper error message on account not active

### ISSUE THREAD

**Issue by amartya-dev** [iMerica/dj-rest-auth#387]
When we authenticate with email and password and the account is not active, the response we get is "Unable to log in with provided credentials", we do have a check later on that explicitly checks for the user "active" status, but the code never reaches there due to the user not being returned from `get_auth_user`

The validator for user status
```python
@staticmethod
    def validate_auth_user_status(user):
        if not user.is_active:
            msg = _('User account is disabled.')
            raise exceptions.ValidationError(msg)
```

Where it fails:
```python
def get_auth_user(self, username, email, password):
        """
        Retrieve the auth user from given POST payload by using
        either `allauth` auth scheme or bare Django auth scheme.

        Returns the authenticated user instance if credentials are correct,
        else `None` will be returned
        """
        if 'allauth' in settings.INSTALLED_APPS:

            # When `is_active` of a user is set to False, allauth tries to return template html
            # which does not exist. This is the solution for it. See issue #264.
            try:
                return self.get_auth_user_using_allauth(username, email, password)
            except url_exceptions.NoReverseMatch:
                msg = _('Unable to log in with provided credentials.')
                raise exceptions.ValidationError(msg)
        return self.get_auth_user_using_orm(username, email, password)
 ```
 
 I guess this is because of the try block or issue #264 
 
 We should be sending the proper error message here IMO

**Comment by amartya-dev** [comment]
A possible solution could be to add a pre-validation of sorts:
```python
# Handle the non active account
    def validate_email(self, value):
        requested_user = User.objects.get(email=value)
        if not requested_user.is_active:
            raise ValidationError("The account is suspended")
        return True
```

**Comment by TheSinghsDen** [comment]
@amartya-dev You can create a custom login serializer and change this behavioud of  the `get_auth_user` function.
```
class CustomLoginSerializer(LoginSerializer):
    """Custom User Login Serializer"""

    # Handle the non active account
    def get_auth_user(self, username, email, password):
        
        if User.objects.filter(email=email).exists():
            requested_user = User.objects.get(email=email)
            if not requested_user.is_active:
                raise exceptions.ValidationError("The account is suspended")
        
        return super().get_auth_user(username, email, password)
```
You will also need to define this serializer in your settings file.
```
REST_AUTH_SERIALIZERS = {
    'LOGIN_SERIALIZER': 'path.to.custom.LoginSerializer',
}
```

**Comment by amartya-dev** [comment]
Hey @TheSinghsDen , thanks for your reply I know we can change the behavior there, it can also be validated via a `validate_email` on the serializer itself as I advocated in my previous comment, the point is, there should be a proper fix for that in the package I guess ... as they are trying to throw a message "Unable account is disabled" in `validate_auth_user_status`.

**Comment by iMerica** [comment]
My preference is to keep it vague, but I would consider any PRs that can give some helpful error message without compromising on security.
