### ISSUE TITLE
How does `drf-yasg` integration work when using JWT?

### ISSUE THREAD

**Issue by Zelzahn** [iMerica/dj-rest-auth#393]
According to [this piece](https://django-rest-framework-simplejwt.readthedocs.io/en/latest/drf_yasg_integration.html) of the Simple JWT documentation, the following code needs to be added. But I do not understand how this works for this library. Does anyone know how to fix this integration? Or does anyone know any documentation that can help me further?

**Comment by iMerica** [comment]
I don't understand your question.
