### ISSUE TITLE
What is this ??? 

### ISSUE THREAD

**Issue by Steve-Dusty** [iMerica/dj-rest-auth#395]
https://github.com/iMerica/dj-rest-auth/blob/master/demo/demo/urls.py

Why do you gotta use re_path ^^^.

This is a warzone in urls.py.
Here, let me teach you how to write URLs.py in django
Normal way: "    path('articles/2003/', views.special_case_2003),"
You call this a "demo" yet you make it so bewildering. How are we supposed to understand this demo when we can't even understand URLs.py? 

Please, follow the normal django way of doing stuff.

**Comment by iMerica** [comment]
Hi @Steve-Dusty,

Typically in open source, developers contribute by writing constructive issue tickets or submitting pull requests. If you want be successful in open source, I would suggest: drop the entitled attitude, be kind and communicate your point in the form of a pull request.
