### ISSUE TITLE
This serializer option is missing in the docs

### ISSUE THREAD

**Issue by yasmin-liban** [iMerica/dj-rest-auth#399]
https://github.com/iMerica/dj-rest-auth/blob/f5079fef6a953d1fcf658b627a08265a62454ac0/dj_rest_auth/app_settings.py#L33

Actually not only this one serializer but the docs don't cover JWT with Expiration Date at all. I had to dive in the source code to find something related. I think It should be mentioned somewhere how to easily set a expiration date for the access token and refresh token.

**Comment by iMerica** [comment]
Pull requests are welcome.
