### ISSUE TITLE
How to create a custom token model properly?

### ISSUE THREAD

**Issue by altry104** [iMerica/dj-rest-auth#401]
Hey there.

I want to create a custom token model , so it can store the data about user-agent, ip_address, and some other stuff.
Apart from that, I am wishing to revoke the tokens, something similar to telegram
![image](https://user-images.githubusercontent.com/79587156/166648221-24ada5a4-67ad-4400-b027-e5e68dcd783f.png)

My problem here is that when I create my own model, declare the custom creation and authentication methods, everything works fine except the registration, because, in default registration view it tries to find user.auth_token, which for some reason does not use my custom token model declared in the settings
![image](https://user-images.githubusercontent.com/79587156/166648648-3bbce4b3-47f5-4025-a529-caa37e5e49e8.png)

When I subclass the Token model from dj-rest-auth, it actually works as well, apart from one thing. In the default model, user is a One to One field, meaning that one user can only have one session active at a time, while I need this to be a foreign key, but I cannot change it when subclassing.

Please help me with that, how do I implement multiple sessions, which store more data than a default Token model and work with all the dj rest views?

**Comment by iMerica** [comment]
Hi I'm closing tickets in this issue tracker that aren't bugs.
