### ISSUE TITLE
ACCOUNT_EMAIL_VERIFICATION = 'mandatory' not honored if rest registration is disabled

### ISSUE THREAD

**Issue by mihqusta** [iMerica/dj-rest-auth#403]
What is the rationale behind the following lines?:

https://github.com/iMerica/dj-rest-auth/blob/f5079fef6a953d1fcf658b627a08265a62454ac0/dj_rest_auth/serializers.py#L131-L132

Current behavior is that if registration via rest is not enabled, login just skips checking if the email is verified. This seems very weird to me and a potential security issue. Certainly not expected behavior.

steps to reproduce:
set 
```
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
```
but leave 
```
# 'dj_rest_auth.registration',
```
out from INSTALLED_APPS.

Make a new account and try logging in: you will get the token without verifying the email!

**Comment by iMerica** [comment]
That was ported from the [original package](https://github.com/Tivix/django-rest-auth/blob/master/rest_auth/serializers.py).

I think the rationale is to only enforce email verification if registration is enabled. Closing for now, but feel free to submit a PR if you think we can make this better.
