### ISSUE TITLE
Reverse for 'password_reset_confirm' not found. 'password_reset_confirm' is not a valid view function or pattern name.

### ISSUE THREAD

**Issue by ahmadzoqi** [iMerica/dj-rest-auth#409]
When i try to reset password with correct email its showes in this error but when i try with wrong email email can be sent !!!

**Comment by anuj-scanova** [comment]
Also getting same above.

<img width="1432" alt="Screen Shot 2022-06-13 at 1 38 40 PM" src="https://user-images.githubusercontent.com/105233146/173308822-6a3fd8f2-8aab-45ff-931e-daf9d2e79c55.png">

**Comment by iarsham** [comment]
check this repo code
https://github.com/iarsham/RestApi-Blog.git

**Comment by Bharath95** [comment]
facing the same issue

**Comment by kurotom** [comment]
> check this repo code https://github.com/iarsham/RestApi-Blog.git

It works for me, thanks.

**Comment by iMerica** [comment]
Closing since this is a configuration issue. Please create a pull request if we can make the documentation or UX more clear.
