### ISSUE TITLE
Google signin using JWT

### ISSUE THREAD

**Issue by mssanaltradebrains** [iMerica/dj-rest-auth#410]
Hi, 
when i'm using one tap signin with google, google sends a JWT token but when i pass that token as access key it throws non key error incorrect value.

{
    "non_field_errors": [
        "Incorrect value"
    ]
}

**Comment by kkuchar2** [comment]
dj-rest-auth social authentication seems to be relying on django-allauth package, and this package still doesn't support new Google Identity Services, that work with JWT tokens. https://github.com/pennersr/django-allauth/issues/3074

**Comment by iMerica** [comment]
Closing since that is not controlled by this package.
