### ISSUE TITLE
Password reset unsuccessful. The password reset link was invalid, possibly because it has already been used. Please request a new password reset.

### ISSUE THREAD

**Issue by mateoKutnjak** [iMerica/dj-rest-auth#412]
When I click on the link that my email received in mail

http://192.168.0.20:8000/reset/3/b6v4qb-257452f2b4dfacae37fd57230078e950/

it redirects me to the page where it says 

```
Password reset unsuccessful

The password reset link was invalid, possibly because it has already been used. Please request a new password reset.
```

What is happening?

**Comment by sourabh0207** [comment]
I am also facing the same issue

**Comment by iMerica** [comment]
We have lots of unit tests on password reset. Please create specific steps to reproduce if the issue persists.
