### ISSUE TITLE
React example using dj-rest-auth and django-allauth for Twitter, Github, Google, etc. login?

### ISSUE THREAD

**Issue by jfornear** [iMerica/dj-rest-auth#413]
Is there a good React example somewhere that uses dj-rest-auth and django-allauth for Twitter, Github, Google, etc. login?

**Comment by iMerica** [comment]
Plenty of tutorials on the web. Let me know which one you like best so maybe we can link to it. 

https://www.google.com/search?q=%22dj-rest-auth%22+Google%7CTwitter%7CFacebook+site%3Adev.to+OR+site%3Amedium.com
