### ISSUE TITLE
Password Change Should Require Old Password

### ISSUE THREAD

**Issue by NyllRE** [iMerica/dj-rest-auth#414]
the route `dj-rest-auth/password/change/` should require old password as far as I know, which isn't included in the prompt. So would there be at least a setting that would make it require the older password first then the new password? It would be a much safer method.

**Comment by wujianguo** [comment]
https://dj-rest-auth.readthedocs.io/en/latest/configuration.html

OLD_PASSWORD_FIELD_ENABLED - set it to True if you want to have old password verification on password change enpoint (default: False)
