### ISSUE TITLE
Add access_token to attr if only code came

### ISSUE THREAD

**Issue by genchik1** [iMerica/dj-rest-auth#417]
For example, when registering on VK, we send only a `code` as a request. But for further actions, we sometimes need an `access_token`. 

I suggest adding `attr['access_token'] = access_token`
in https://github.com/iMerica/dj-rest-auth/blob/master/dj_rest_auth/registration/serializers.py#L134

**Comment by iMerica** [comment]
Pull requests are welcome. Closing this to tidy up the issue tracker.

**Comment by genchik1** [comment]
@iMerica So can I take on this task?
