### ISSUE TITLE
Is dj-rest-auth compatible with Django ver4?

### ISSUE THREAD

**Issue by helpme1** [iMerica/dj-rest-auth#418]
In the requirements, it states "Django 2 or 3". Does it mean dj-rest-auth is not compatible with Django ver 4?

**Comment by lesreaper** [comment]
Does not seem that it is. Throwing this error on install for me:

ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' 

I would update, but it seem this project has been abandoned.

**Comment by iMerica** [comment]
The official deps have always been >= Django 2. I've updated the README to clarify that. Also see the test results:

https://app.circleci.com/pipelines/github/iMerica/dj-rest-auth/191/workflows/9accfda0-7d88-4e2a-915f-b3ab917e019b/jobs/303
