### ISSUE TITLE
Settings variable for enabling/disabling use of allauth forms/emails

### ISSUE THREAD

**Issue by kut** [iMerica/dj-rest-auth#419]
There are a number of challenges that arise when we have `allauth` in our `INSTALLED_APPS` but don't want to use its email templates/password reset functionality, for instance #367. Could we have a settings toggle that allows us to very easily fix all these issues?

Essentially, anywhere we have:
```
if 'allauth' in settings.INSTALLED_APPS:
    foo()
```

...we should replace with:

```
if settings.REST_AUTH_USE_ALLAUTH and 'allauth' in settings.INSTALLED_APPS:
   foo()
```

Thoughts?

**Comment by iMerica** [comment]
I get how that could be tidier, but it's yet another flag in this library to maintain and test. Going to close this for now to keep the issue tracking clean.

**Comment by victormoyanodiaz** [comment]
Hey @kut and @iMerica, 

Following @kut suggestion, I just created a PR to fix this particular issue. The only thing is I didn't create any new flag to fix this functionality. Only checking if the user is trying to use a custom_email_template should be more than enought, right?

Any thoughts on this? We are stuck with version 2.1.4 until this is fixed, sadly.

Thanks in advance!
