### ISSUE TITLE
Python requests request throwing b'{"detail":"Authentication credentials were not provided."}' all the time

### ISSUE THREAD

**Issue by Dotolox** [iMerica/dj-rest-auth#420]
```
import requests
from requests.structures import CaseInsensitiveDict

url = "http://127.0.0.1:8000/dj-rest-auth/user/"

headers = CaseInsensitiveDict()
headers["Authorization"] = "Token xxxxxxxxxxxxxxxxxxxxxxxxxxx"


resp = requests.get(url, headers=headers)

print(resp.status_code)
```
If tried lots and lots of Python requests variants but no matter which request I sent to the user endpoint it throws the `b'{"detail":"Authentication credentials were not provided."}'` all the time, although Authorization headers where passed.

This example: 
```
headers = {'Authorization': 'Token xxxxxxxxxxxxxxxxxxxxxxxxxxx', 'content-type': 'application/json', 'Accept': 'application/json'}
r = requests.get("http://127.0.0.1:8000/dj-rest-auth/user/", headers=headers, timeout=5)
print(r.content)
```
throws the same error. What am I missing?

**Comment by iMerica** [comment]
This seems like a configuration issue on your end. I'm closing all support related issues so that actual bugs are surfaced and more visible.
