### ISSUE TITLE
JWT - /logout Doesn't Delete Cookies

### ISSUE THREAD

**Issue by Dresdn** [iMerica/dj-rest-auth#435]
When the two settings are used, the JWT AUTH cookies aren't deleted since the `secure` flag isn't set.

```
JWT_AUTH_SAMESITE = 'None'
JWT_AUTH_SECURE = True
```
The logic in `dj_rest_auth.jwt_auth.unset_jwt_cookies()` hard codes the `samesite` attribute of `delete_cookie()`, which causes the `secure` flag to not be set, causing the browser to not delete them.

I'll open a PR shortly to fix.

**Comment by DarnellSylvain** [comment]
Is there anyway I can use this myself before it is pulled?
