### ISSUE TITLE
When using social login, how to detect on the frontend app if its the first time the user logs in or not?

### ISSUE THREAD

**Issue by adrenaline681** [iMerica/dj-rest-auth#472]
I'm using social login with Facebook and Google. On my frontend, I would like to detect if it's the first time the user logs in or not to be able to send them to different routes in each case. How would I approach this?

**Comment by zafercuz** [comment]
Back on our work project, we had this kind of feature. We just added a column say for an example "`first_login (DATETIME)`" on the **USER** table. Then everytime the user logins, we just call that endpoint to check if it's the user's first login or not.

Or I'm totally misunderstanding your question here.
