### ISSUE TITLE
Login Response is not returning refresh-token in dj-rest-auth v3.0.0

### ISSUE THREAD

**Issue by marcosdon28** [iMerica/dj-rest-auth#485]
I have been using dj-rest-auth for a while, i installed the version 3.0.0 in my current project and it is not working properly.
When i login a user the response return an empty string instead of a refresh.
My solution was downgrading to and old version that i know thar works well (2.2.4)

{
    "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjc3MTU5NzE4LCJpYXQiOjE2NzY1NTk3MTgsImp0aSI6Ijk2Y2M3NDZmM2ZmOTQ3NWRiYzBmMGVkYzFlYTYyYmY2IiwidXNlcl9pZCI6MX0.rgrJVCs0kgxgU7h6G6lsI-mSly6IZJULQEIh0vQ9lSA",
    "refresh_token": "",
    "user": {
        "pk": 1,
        "username": "admin",
        "email": "EMAIL",
        "first_name": "Pepe",
        "last_name": "1234"
    }
}
It is an example for the response of version 3.0.0, the request show it empty but the cookie for the refresh token seems to be updated.
![image](https://user-images.githubusercontent.com/74331195/219402465-4e0e8c0f-cdca-4f56-8c51-43902aff29ec.png)

My project config is :
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'dj_rest_auth.jwt_auth.JWTCookieAuthentication',
        
    ],

    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    
}

REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_COOKIE': 'my-app-auth',
    'JWT_AUTH_REFRESH_COOKIE': 'my-refresh-token',
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=10000),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=10),
    'ROTATE_REFRESH_TOKENS' : True,
}

**Comment by Skm1221** [comment]
If you add `"JWT_AUTH_HTTPONLY": False`, it will work.

```
REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_HTTPONLY": False,
    ...
}
```

**Comment by MarcoGlauser** [comment]
We had the same issue with version 3.0. Setting `JWT_AUTH_HTTPONLY` to `False` did the trick. 

This line is probably causing the issue, since it previously defaulted to False for `JWT_AUTH_HTTPONLY` and the refresh token is set right after.
https://github.com/iMerica/dj-rest-auth/compare/2.2.8...3.0.0#diff-6605a895156338ef26e802ff3d8fd57aa730b05e9340402bf69cd0a823e4b9dbL92

**Comment by kiraware** [comment]
Sorry for late response. Actually, i already add a note about this behaviour in docs here https://dj-rest-auth.readthedocs.io/en/latest/configuration.html#jwt-auth-httponly.

**Comment by marcosdon28** [comment]
> 

Thank you guys for you support !
