### ISSUE TITLE
app Settings Configuration

### ISSUE THREAD

**Issue by aaxbut** [iMerica/dj-rest-auth#491]
In documentation https://dj-rest-auth.readthedocs.io/en/latest/configuration.html#configuration for customizing serializer need to specify in `REST_AUTH` but in code `app_settings` for customizing serializer need specify `REST_AUTH_SERIALIZERS` for it.
may need change documentation or some else?

**Comment by kiraware** [comment]
Can you explain more? Because `REST_AUTH_SERIALIZERS` is removed in 3.0.0. What is your `dj-rest-auth` version?

**Comment by aaxbut** [comment]
@kiraware ok, my version is 2.2.5... update, thx

**Comment by kiraware** [comment]
Your welcome :)
