### ISSUE TITLE
Error: "allauth needs to be added to INSTALLED_APPS" after upgrading to django-allauth v0.55.0

### ISSUE THREAD

**Issue by brandon-kong** [iMerica/dj-rest-auth#534]
Due to a backwards-incompatible change in django-allauth's new v0.55.0, dj_rest_auth does not work with the newest version of allauth. django-allauth's [v0.55.0 does NOT have a function "email_address_exists"](https://github.com/pennersr/django-allauth/blob/main/ChangeLog.rst#backwards-incompatible-changes) in `allauth/utils.py`  which is what is causing dj_rest_auth to throw an error in the first place. 

How I reproduced:
1. In my Django project, I installed the latest versions of both allauth and dj-rest-auth with `pip install django-allauth dj-rest-auth`.
2. Add the appropriate apps inside `INSTALLED_APPS`. For reference, I added this to mine: 
```py
[
...
'django.contrib.sites',
'allauth',
'allauth.account',
'allauth.socialaccount',
'allauth.socialaccount.providers.google',

'dj_rest_auth',
'dj_rest_auth.registration',
...
]
```
3. In one of my apps' `views.py`, I imported `from dj_rest_auth.registration.views import SocialLoginView`.
4. After running `py manage.py makemigrations` or `py manage.py runserver`, etc... I received 
```bash
ImportError: allauth needs to be added to INSTALLED_APPS
```
I tried:
- downgrading to django-allauth v0.54.0 and the error went away

The error comes from:
`dj_rest_auth/registration/serializers.py`

The expected output should be an errorless migration, but instead I cannot interact with any parts of my application

I created a minimal Django project with the same configurations and pip package versions that I tested above:
https://github.com/brandon-kong/dj_rest_auth_issue

**Comment by jalalsadeghi** [comment]
You need to change your requirements.

django-allauth>=0.24.1<0.55.0

or 

pip install django-allauth==0.54.0
