### ISSUE TITLE
allauth.account.middleware.AccountMiddleware must be added to settings.MIDDLEWARE in the demo project

### ISSUE THREAD

**Issue by daniel-unyi-42** [iMerica/dj-rest-auth#555]
It doesn't work otherwise.

**Comment by RonaldinhoL** [comment]
same

**Comment by RonaldinhoL** [comment]
nvm, just add `allauth.account.middleware.AccountMiddleware` to middleware

**Comment by ozgurturkiye** [comment]
Does order matter when adding "middleware"?

**Comment by mweinelt** [comment]
> Does order matter when adding "middleware"?

https://github.com/pennersr/django-allauth/blob/main/allauth/account/apps.py#L13-L17

The test here does not care for the order.

**Comment by colinkingswood** [comment]
This ought to be added to the documentation.
