### ISSUE TITLE
EmailAddressManager object has no attrubute 'is_verified'

### ISSUE THREAD

**Issue by MMf-mmf** [iMerica/dj-rest-auth#573]
when using the registration endpoint I'm getting this error when attempting to register a new user,
AttributeError: 'EmailAddressManager' object has no attribute 'is_verified'

if I reverse the code to the way it was before commit 725879b it works fine

<img width="1336" alt="image" src="https://github.com/iMerica/dj-rest-auth/assets/65723183/b943edf9-8cd3-4834-bb28-06e1ce87f5fc">

any thoughts?

**Comment by flange-ipb** [comment]
See [#538](https://github.com/iMerica/dj-rest-auth/issues/538#issuecomment-1752975977).
