### ISSUE TITLE
 How to change activate_url in dj-rest-auth after registration?

### ISSUE THREAD

**Issue by amnasanu** [iMerica/dj-rest-auth#620]
I'm using dj-rest-auth in my Django project for authentication, and after registration, it sends an activation email with a verification link. The problem is, the verification link is pointing to http://127.0.0.1:8000/registration/verify-email-address/NDU:1ry1MB:ky6ajCYa9gkdGffVSrG3HOZMe_pfjwWXSdCLrEYfL9I/, but I want it to point to http://localhost:3000/registration/verify-email-address/NDU:1ry1MB:ky6ajCYa9gkdGffVSrG3HOZMe_pfjwWXSdCLrEYfL9I/.

I've searched through the dj-rest-auth documentation and settings but couldn't find any configuration option to modify the activate_url. Is there a way to change this URL to point to my frontend URL (http://localhost:3000) instead of the default one?

Any help or guidance would be greatly appreciated. Thank you!

**Comment by iMerica** [comment]
Hi there, can you please move this to the Q&A section of the [discussions](https://github.com/iMerica/dj-rest-auth/discussions) area?
