### ISSUE TITLE
Password Reset Custom Email

### ISSUE THREAD

**Issue by imnileshd** [iMerica/dj-rest-auth#623]
Hello Team,

Could you please guide on how to customize the passwords reset email template in latest version? I have referred the previous issues but none of them are working for me.

Thanks in Advance!

**Comment by gleniat** [comment]
If you also use django-allauth: 
You can try to add the `/templates/account/email/password_reset_key_message.txt` file

```
{% extends "account/email/base_message.txt" %}
{% load i18n %}

{% block content %}{% autoescape off %}{% blocktrans %}YOUR CUSTOM TEXT HERE .... You're receiving this email because you or someone else has requested a password reset for your user account. It can be safely ignored if you did not request a password reset. Click the link below to reset your password.{% endblocktrans %}

{{ password_reset_url }}{% if username %}

{% blocktrans %}In case you forgot, your username is {{ username }}.{% endblocktrans %}{% endif %}{% endautoescape %}{% endblock content %}
```

This overrides the allauth template. This works.
Other templates are here: https://github.com/pennersr/django-allauth/tree/main/allauth/templates/account/email

If you don't use django-allauth: I don't know how atm.
