### ISSUE TITLE
`django-allauth` >= v64.0.0 support

### ISSUE THREAD

**Issue by dpgraham4401** [iMerica/dj-rest-auth#646]
[Django Allauth recently released their first stable version](https://docs.allauth.org/en/latest/release-notes/recent.html), from 0.63.6 to 64.0.0. It's worth noting he says in the release notes that they may continue to introduce minor breaking changes in minor version.

I haven't tested whether there are problems from upgrading to >= 64.0.0 yet.

**Comment by semihsezer** [comment]
Yes it would be great to become compatible with the latest Django Allauth! 
Are there known incompatibilities or issues that we need to fix?

**Comment by dpgraham4401** [comment]
The only listed backwards incompatible change listed in django-allauth's 64.0.0 release notes is they dropped support to django < 4.1. https://docs.allauth.org/en/latest/release-notes/recent.html#id2

I will test against the lastest version and submit a PR if I don't find any problems.

**Comment by Saman-Zand-H** [comment]
hello, anything done about doing this compatibly? it's been about 6 months since 0.62.0, where the social login integrations started to break, but no compatibly change has been done ever since
