### ISSUE TITLE
UID for password reset incorrectly uses base64

### ISSUE THREAD

**Issue by gsheni** [iMerica/dj-rest-auth#76]
When a password reset link is request, the UID is encoded into the url as such, by `django allauth`
```tex
/accounts/password/reset/key/7w-1x7-d1a11z1sa1s1a1s/
```
Such that the uid is `7w` and the token is `1x7-d1a11z1sa1s1a1s`

The UID is encoded here, as **base36**:
https://github.com/pennersr/django-allauth/blob/330bf899dd77046fd0510221f3c12e69eb2bc64d/allauth/account/forms.py#L524

However, when the UID decoded in `django-rest-auth` as **base64**
https://github.com/jazzband/dj-rest-auth/blob/02c9242e3d069164692ef44a0f15eaca31a41cac/dj_rest_auth/serializers.py#L214

**Comment by iMerica** [comment]
How does this manifest into an actual problem? Like, Is there an exception raised? Or is there a 404? 

We have tests on password reset and they're all passing.

**Comment by mr-engin3er** [comment]
When a password reset link is request, the UID is encoded into the url as such, by django allauth

`password-reset/confirm/NDc/5m9-db35d6f0efc16645b352/`

Here UID is **NDc**
And token is **5m9-db35d6f0efc16645b352**

**Comment by gsheni** [comment]
@squio see this pull request: https://github.com/Tivix/django-rest-auth/pull/643

I had originally closed the PR because it wasn't being merged in.

**Comment by squio** [comment]
Hi @iMerica what is the status of this issue and the associated PR?

As far as I can tell this does not introduce a hard dependency on Allauth, while still providing compatibility with the password reset scheme when Allauth *is* available.

That is exactly the use case I currently have, so it would be really helpful if this PR got integrated.
Do you have any plans and a time line if so?

**Comment by iMerica** [comment]
That PR has some failing tests.

**Comment by squio** [comment]
Hmm @gsheni are you still interested in this PR? 

Otherwise I'll have a look and see if I can make fixes and maybe extra unit tests

**Comment by gsheni** [comment]
@squio you can go ahead and take over my PR.

**Comment by squio** [comment]
So I finally got around it and got it fixed in #266.

After closely inspecting the code the fix was not complicated (tests should use the right encoder corresponding to the decoder used in the Serializer class.

Also the selection of encoder / decoder is now similar to the other checks where we test if allauth is in installed apps.

**Comment by squio** [comment]
Thanks 👍

**Comment by kut** [comment]
@iMerica should this actually be a setting, and not just based on whether `allauth` is installed? In our use case, we have `allauth` installed but not used to generate the UID/token for password resets _(we're using the default `dj-rest-auth` functionality which relies on `PasswordResetForm` which is in Django core)_. Surely having `allauth` installed doesn't necessarily dictate that it will be used for password reset purposes?

(One could also certainly imagine an errant and unused installation of `allauth` in your environment, eg in a dependency, which would alter the above decoding functionality.)

Could this instead be a setting (called something like `REST_USE_ALLAUTH_UID_DECODER`) that allows you to concretely specify which decoder to use?

(The result for us it that we cannot use `dj-rest-auth` v2.1.6 onwards.)

**Comment by KaczuH** [comment]
Unfortunately the problem persists. Uid is generated by Django related code in `PasswordResetForm` and decoded by `allauth` in `PasswordResetConfirmSerializer`

Updated tests in #266 assume in `_generate_uid_and_token` uid and token are generated by allauth. Which is not the case after conducting manual test.

**Comment by squio** [comment]
Hmm indeed, this patch didn't solve my real world issue either; now reverted to an intermediate view to catch the difference in encoding.

For anyone interested:
- decode the Django standard tokens
- if valid, encode using allauth's strategy
- redirect to allauth reset password view

https://gist.github.com/squio/28aadec528bea9302c168744fd0af3b6

**Comment by georgkrause** [comment]
@iMerica Would you accept a patch that enforces the Django encoding of the UID instead of only checking for weather or not allauth is installed?
